---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: q-server
  name: q-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: q-server
  template:
    metadata:
      labels:
        io.kompose.service: q-server
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: qserver
        image: senegal/tonlabs-q-server:latest
        name: q-server
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: "0.3"
            memory: 0.5Gi
        ports:
        - containerPort: 4000
