apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    io.kompose.service: q-server
  name: q-server-ton
spec:
  ports:
  - name: "4000"
    port: 4000
    targetPort: 4000
  selector:
    io.kompose.service: q-server
