---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: q-server
  name: q-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: q-server
  template:
    metadata:
      labels:
        io.kompose.service: q-server
    spec:
      containers:
      - env:
        - name: Q_DATABASE_MAX_SOCKETS
          value: "100"
        - name: Q_DATABASE_SERVER
          value: arangodb:8529
        - name: Q_REQUESTS_MODE
          value: kafka
        - name: Q_REQUESTS_SERVER
          value: kafka-ton:9092
        - name: Q_REQUESTS_TOPIC
          value: requests
        - name: Q_SLOW_DATABASE_MAX_SOCKETS
          value: "20"
        - name: Q_SLOW_DATABASE_SERVER
          value: arangodbni:8529
        - name: Q_STATSD_SERVER
          value: statsd:9125
        - name: VIRTUAL_HOST
          value: q-server-ton
        - name: VIRTUAL_PORT
          value: "4000"
        image: senegal/tonlabs-q-server:latest
        name: q-server
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: "0.3"
            memory: 0.5Gi
        ports:
        - containerPort: 4000
