---
- debug: var=hostvars[groups['kube-master'][0]]['kubeadm_token']

- name: Joining control plane node to the cluster.
  shell: >-
    timeout -k 300s 300s
    kubeadm join
    {{ control_plane_endpoint | default(hostvars[groups['kube-master'][0]]['ansible_default_ipv4']['address']) }}:{{ control_plane_port }}
    --token {{ hostvars[groups['kube-master'][0]]['kubeadm_token'] }}
    --discovery-token-ca-cert-hash sha256:{{ hostvars[groups['kube-master'][0]]['ca_cert_hash'] }}
    --control-plane 
    --certificate-key {{ hostvars[groups['kube-master'][0]]['control_plane_token'] }}
    --v=5
  any_errors_fatal: true
  register: kubeadm_join_control_plane
  retries: 3
  until: kubeadm_join_control_plane is succeeded
