---
- name: Include vars
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - default.yaml

- name: "Install docker"
  shell: 'curl -fsSL https://get.docker.com | sh'

- name: Load kernel modules 
  include_tasks: modules.yml 

- name: Disable system swap
  shell: "swapoff -a"

- name: Remove current swaps from fstab
  lineinfile:
    dest: /etc/fstab
    regexp: '(?i)^([^#][\S]+\s+(none|swap)\s+swap.*)'
    line: '# \1'
    backrefs: yes
    state: present

- name: Disable swappiness and pass bridged IPv4 traffic to iptable's chains, enable ip forwarding
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
    sysctl_set: yes
  with_items:
    - { name: 'vm.swappiness', value: '0' }
    - { name: 'net.bridge.bridge-nf-call-iptables', value: '1' }
    - { name: 'net.ipv4.ip_forward', value: '1' }

- name: be sure firewalld is disabled
  systemd: name=firewalld enabled=no
  ignore_errors: yes

- name: be sure firewalld is stopped
  systemd: name=firewalld state=stopped
  ignore_errors: yes

