---
- name: "reboot server"
  shell: sleep 2 && shutdown -r now "Ansible updates triggered" 
  async: 1
  poll: 0
  ignore_errors: true

- name: waiting for the server to come back
  wait_for_connection:
    timeout: 360
    delay: 20
