---
apiVersion: v1
data:
  {{- toYaml .Values.zookeeper | nindent 2 }}
kind: ConfigMap
metadata:
  name: zookeeper

---
apiVersion: v1
data:
  {{- toYaml .Values.kafka | nindent 2 }}
kind: ConfigMap
metadata:
  name: kafka

---
apiVersion: v1
data:
  {{- toYaml .Values.connect | nindent 2 }}
kind: ConfigMap
metadata:
  name: connect

---
apiVersion: v1
data:
  {{- toYaml .Values.schemaregistry | nindent 2 }}
kind: ConfigMap
metadata:
  name: schemaregistry
