---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: check-connect
  name: check-connect
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: check-connect
  template:
    metadata:
      labels:
        io.kompose.service: check-connect
    spec:
      containers:
      - image: senegal/tonlabs-kafka-check-connect:latest
        name: check-connect
        resources:
          limits:
            cpu: "1"
            memory: 1.5Gi
          requests:
            cpu: "0.2"
            memory: 0.5Gi
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: connect
  name: connect
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: connect
  template:
    metadata:
      labels:
        io.kompose.service: connect
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: connect
        image: senegal/confluentinc-cp-kafka-connect:5.3.1
        name: connect
        resources:
          limits:
            cpu: "1"
            memory: 1.5Gi
          requests:
            cpu: "0.2"
            memory: 0.5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: kafka
  name: kafka-ton
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka
  template:
    metadata:
      labels:
        io.kompose.service: kafka
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: kafka
        image: confluentinc/cp-kafka:5.3.1
        name: kafka-ton
        resources:
          limits:
            cpu: "1"
            memory: 1.5Gi
          requests:
            cpu: "0.2"
            memory: 0.5Gi
        ports:
        - containerPort: 9092

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: schema-registry
  name: schema-registry-ton
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: schema-registry
  template:
    metadata:
      labels:
        io.kompose.service: schema-registry
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: schemaregistry
        image: confluentinc/cp-schema-registry:5.3.1
        name: schema-registry-ton
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: "1"
            memory: 1.5Gi
          requests:
            cpu: "0.2"
            memory: 0.5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: zookeeper
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: zookeeper
  template:
    metadata:
      labels:
        io.kompose.service: zookeeper
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: zookeeper
        image: confluentinc/cp-zookeeper:5.3.1
        name: zookeeper
        resources:
          limits:
            cpu: "1"
            memory: 1.5Gi
          requests:
            cpu: "0.2"
            memory: 0.5Gi
        ports:
        - containerPort: 2181
