---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: node
  name: node
spec:
  ports:
  - name: "30303"
    port: 30303
    protocol: UDP
    targetPort: 30303
  selector:
    io.kompose.service: node
