---
apiVersion: v1
kind: Service
metadata:
  name: arangodbni
spec:
  ports:
  - name: "8529"
    port: 8529
    targetPort: 8529
  selector:
    app: arangodbni

---
apiVersion: v1
kind: Service
metadata:
  name: arangodb
spec:
  ports:
  - name: "8529"
    port: 8529
    targetPort: 8529
  selector:
    app: arangodb
